import type { Product } from '@/types'

/*
  BESMA SEVDAM — Demo product catalog.
  Used as fallback when the database is not yet connected.
  All images: Unsplash beauty photography.
  Variant products use stock:0 — individual stock lives on each variant.
*/

export const DEMO_PRODUCTS: Product[] = [

  /* ─────────────── LIPS ─────────────── */
  {
    id: 'demo-001',
    name_en: 'Velvet Matte Lipstick',
    name_ar: 'أحمر شفاه مخملي غير لامع',
    slug: 'velvet-matte-lipstick',
    description_en: 'An ultra-velvety matte finish that stays flawless for up to 12 hours. This weightless formula moulds to your lips, delivering rich pigment that complements every skin tone beautifully.',
    description_ar: 'نعومة مخملية استثنائية بتثبيت مطفأ يدوم حتى 12 ساعة. تركيبة خفيفة الوزن تمنح لون غني يناسب جميع درجات البشرة.',
    price: 145,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4e6232bf2ebb?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'v-001-1', productId: 'demo-001', shadeName: 'Rose Nude',    hexColor: '#C4927A', image: null, stock: 42, sku: 'VML-RN', sortOrder: 0 },
      { id: 'v-001-2', productId: 'demo-001', shadeName: 'Berry Bliss',  hexColor: '#8B3A52', image: null, stock: 28, sku: 'VML-BB', sortOrder: 1 },
      { id: 'v-001-3', productId: 'demo-001', shadeName: 'Dusty Rose',   hexColor: '#D4A0A7', image: null, stock: 36, sku: 'VML-DR', sortOrder: 2 },
      { id: 'v-001-4', productId: 'demo-001', shadeName: 'Deep Plum',    hexColor: '#4A1A2C', image: null, stock: 19, sku: 'VML-DP', sortOrder: 3 },
      { id: 'v-001-5', productId: 'demo-001', shadeName: 'Coral Fever',  hexColor: '#E8735A', image: null, stock: 0,  sku: 'VML-CF', sortOrder: 4 },
      { id: 'v-001-6', productId: 'demo-001', shadeName: 'Terracotta',   hexColor: '#C97D5A', image: null, stock: 24, sku: 'VML-TC', sortOrder: 5 },
    ],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['lipstick', 'matte', 'nude', 'long-lasting', 'bestseller'],
    benefits: 'Long-wear formula that stays comfortable throughout the day. Deeply pigmented for true-colour payoff in a single swipe. Enriched with Vitamin E to keep lips soft and nourished. Non-drying — glides on effortlessly without tugging.',
    ingredients: 'Isododecane, Dimethicone, Trimethylsiloxysilicate, Tocopherol (Vitamin E), Candelilla Wax, Castor Oil, Mica, CI 15850, CI 77891.',
    usage: 'Line and fill lips with a lip liner for extended wear. Apply directly from bullet or use a lip brush for precision. Layer for deeper colour intensity. Blot with a tissue for an ultra-matte long-wear finish.',
    isBestseller: true,
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-002',
    name_en: 'Luxury Liquid Lipstick',
    name_ar: 'أحمر شفاه سائل فاخر',
    slug: 'luxury-liquid-lipstick',
    description_en: 'A statement colour that commands the room. This ultra-pigmented liquid lipstick sets to a bold, transfer-proof matte finish with the comfort of a serum.',
    description_ar: 'أحمر قاطع يلفت الأنظار. أحمر شفاه سائل فائق التصبغ يثبت بلمسة مطفأة لا تنتقل، بريحة المصل.',
    price: 165,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1631214524020-3c69888e0a66?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'v-002-1', productId: 'demo-002', shadeName: 'Ruby Red',       hexColor: '#9B1C1C', image: null, stock: 28, sku: 'LLL-RR', sortOrder: 0 },
      { id: 'v-002-2', productId: 'demo-002', shadeName: 'Cherry Bomb',    hexColor: '#C41E3A', image: null, stock: 22, sku: 'LLL-CB', sortOrder: 1 },
      { id: 'v-002-3', productId: 'demo-002', shadeName: 'Classic Scarlet', hexColor: '#CC0000', image: null, stock: 35, sku: 'LLL-CS', sortOrder: 2 },
      { id: 'v-002-4', productId: 'demo-002', shadeName: 'Dark Raspberry', hexColor: '#872657', image: null, stock: 14, sku: 'LLL-DK', sortOrder: 3 },
    ],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['liquid lipstick', 'red', 'bold', 'transfer-proof', 'matte'],
    benefits: 'Transfer-proof and kiss-proof formula that lasts up to 16 hours. High-density pigment delivers full colour coverage in one layer. Serum-infused base keeps lips comfortable and hydrated throughout wear.',
    ingredients: 'Aqua, Dimethicone, Cyclopentasiloxane, Acrylates Copolymer, Glycerin, Hyaluronic Acid, CI 15850 (Red 7), CI 77891, Tocopherol Acetate.',
    usage: 'Start from the centre of your upper lip and follow the natural lip line. Fill in with the wand in smooth, even strokes. Allow 60 seconds to fully set before pressing lips together.',
    isBestseller: true,
    createdAt: new Date('2025-10-05'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-003',
    name_en: 'Long-Lasting Lip Gloss – Soft Pink',
    name_ar: 'جلوس شفاه طويل الأمد – وردي ناعم',
    slug: 'long-lasting-lip-gloss-soft-pink',
    description_en: 'A glass-like high-gloss formula that plumps and illuminates lips with a non-sticky, feather-light texture. Sheer pink tones with golden shimmer particles catch the light at every angle.',
    description_ar: 'تركيبة عالية اللمعان تشبه الزجاج تُكبِّر الشفتين وتُضيئهما بملمس خفيف لا يُلتصق.',
    price: 98,
    stock: 65,
    imageUrl: 'https://images.unsplash.com/photo-1620803366004-119b57f54cd6?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['lip gloss', 'pink', 'plumping', 'shimmer', 'glossy'],
    benefits: 'Hyaluronic acid plumping complex visibly enhances lip volume. Non-sticky, lightweight texture feels comfortable for all-day wear. Vitamin C brightens natural lip tone over time.',
    ingredients: 'Polybutene, Hydrogenated Polyisobutene, Dipentaerythrityl Hexacaprylate, Hyaluronic Acid, Ascorbyl Glucoside (Vitamin C), Mica, CI 15850, CI 77000.',
    usage: 'Apply directly from the doe-foot applicator, starting at the centre and sweeping outward. Layer over your favourite lipstick for extra dimension, or wear alone for a fresh, glossy look.',
    isBestseller: false,
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-004',
    name_en: 'Hydrating Lip Balm – Natural Glow',
    name_ar: 'مرطب شفاه مرطب – بريق طبيعي',
    slug: 'hydrating-lip-balm-natural-glow',
    description_en: 'A nourishing lip treatment infused with rosehip oil, shea butter, and pure gold flecks that leave lips silky, plump, and luminously dewy. Your everyday luxury in a sleek gold tube.',
    description_ar: 'علاج مغذٍ للشفاه بزيت ثمر الورد وزبدة الشيا وجزيئات الذهب الخالص لشفاه حريرية ومضيئة.',
    price: 78,
    stock: 90,
    imageUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8bf70ad9?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['lip balm', 'hydrating', 'rosehip', 'shea butter', 'natural'],
    benefits: 'Rosehip oil repairs and regenerates delicate lip skin overnight. Shea butter provides deep, long-lasting moisture barrier. 24-hour hydration formula prevents chapping and cracking.',
    ingredients: 'Cera Alba (Beeswax), Helianthus Annuus (Sunflower) Seed Oil, Rosa Canina (Rosehip) Fruit Oil, Butyrospermum Parkii (Shea) Butter, Tocopherol, Vanilla Planifolia Fruit Extract.',
    usage: 'Apply generously to clean lips whenever needed. Use as an overnight mask for intense repair — apply a thick layer before sleeping. Layer under lipstick to prime lips and extend colour wear.',
    isBestseller: false,
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2025-12-01'),
  },

  /* ─────────────── FACE ─────────────── */
  {
    id: 'demo-005',
    name_en: 'Soft Matte Foundation SPF 30',
    name_ar: 'كريم أساس ناعم غير لامع بحماية شمسية 30',
    slug: 'soft-matte-foundation-spf30',
    description_en: 'A skin-perfecting matte foundation with SPF 30 protection that blurs imperfections and evens skin tone for a naturally flawless look. Buildable coverage from medium to full — never cakey, never heavy.',
    description_ar: 'كريم أساس مطفأ يحمي من الشمس ويطمس العيوب ويوحد لون البشرة لمظهر طبيعي مثالي.',
    price: 295,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'v-005-1', productId: 'demo-005', shadeName: 'Porcelain',      hexColor: '#F5E8D5', image: null, stock: 30, sku: 'SMF-PC', sortOrder: 0 },
      { id: 'v-005-2', productId: 'demo-005', shadeName: 'Ivory',          hexColor: '#F2DABB', image: null, stock: 35, sku: 'SMF-IV', sortOrder: 1 },
      { id: 'v-005-3', productId: 'demo-005', shadeName: 'Sand',           hexColor: '#E8C99B', image: null, stock: 40, sku: 'SMF-SA', sortOrder: 2 },
      { id: 'v-005-4', productId: 'demo-005', shadeName: 'Golden Beige',   hexColor: '#D4A96A', image: null, stock: 28, sku: 'SMF-GB', sortOrder: 3 },
      { id: 'v-005-5', productId: 'demo-005', shadeName: 'Warm Caramel',   hexColor: '#C48B5A', image: null, stock: 22, sku: 'SMF-WC', sortOrder: 4 },
      { id: 'v-005-6', productId: 'demo-005', shadeName: 'Deep Espresso',  hexColor: '#6B3A28', image: null, stock: 18, sku: 'SMF-DE', sortOrder: 5 },
    ],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['foundation', 'matte', 'SPF 30', 'buildable', 'coverage', 'bestseller'],
    benefits: 'Buildable coverage from medium to full without heaviness. SPF 30 broad-spectrum protection shields from UV damage daily. Oil-control technology keeps skin matte for up to 14 hours.',
    ingredients: 'Aqua, Cyclopentasiloxane, Titanium Dioxide (CI 77891), Dimethicone, Zinc Oxide, Niacinamide, Glycerin, Silica, Phenoxyethanol, Iron Oxides (CI 77491, CI 77492, CI 77499).',
    usage: 'Apply to clean, moisturised skin using a foundation brush or beauty blender. Start from the centre of the face and blend outward. Build coverage where needed.',
    isBestseller: true,
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-006',
    name_en: 'Full Coverage Concealer',
    name_ar: 'كونسيلر تغطية كاملة',
    slug: 'full-coverage-concealer',
    description_en: 'A creamy, full-coverage concealer that erases dark circles, blemishes, and redness instantly. Flexible coverage that moves with your skin — no creasing, no settling into fine lines.',
    description_ar: 'كونسيلر كريمي بتغطية كاملة يمحو الهالات السوداء والبثور والاحمرار على الفور.',
    price: 195,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'v-006-1', productId: 'demo-006', shadeName: 'Ivory',    hexColor: '#F5EBD8', image: null, stock: 45, sku: 'FCC-IV', sortOrder: 0 },
      { id: 'v-006-2', productId: 'demo-006', shadeName: 'Beige',    hexColor: '#EDD4AA', image: null, stock: 50, sku: 'FCC-BG', sortOrder: 1 },
      { id: 'v-006-3', productId: 'demo-006', shadeName: 'Sand',     hexColor: '#D4B887', image: null, stock: 38, sku: 'FCC-SA', sortOrder: 2 },
      { id: 'v-006-4', productId: 'demo-006', shadeName: 'Honey',    hexColor: '#C49A60', image: null, stock: 30, sku: 'FCC-HN', sortOrder: 3 },
      { id: 'v-006-5', productId: 'demo-006', shadeName: 'Chestnut', hexColor: '#A67848', image: null, stock: 20, sku: 'FCC-CH', sortOrder: 4 },
    ],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['concealer', 'full coverage', 'dark circles', 'no crease'],
    benefits: 'Full coverage that conceals dark circles, hyperpigmentation and blemishes in a single layer. Flexible formula moves with skin — no settling into fine lines or creasing. Caffeine-infused to de-puff and brighten under eyes.',
    ingredients: 'Cyclopentasiloxane, Dimethicone, Isododecane, Trimethylsiloxysilicate, Caffeine, Niacinamide, Peptides Complex, Iron Oxides, Titanium Dioxide (CI 77891).',
    usage: 'Tap a small amount under eyes or on blemishes using your ring finger or a concealer brush. Blend gently by tapping — avoid rubbing. Set with a translucent or setting powder for extended wear.',
    isBestseller: false,
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-007',
    name_en: 'Radiance Compact Powder',
    name_ar: 'بودرة مضغوطة للإشراق',
    slug: 'radiance-compact-powder',
    description_en: 'A finely milled setting powder that gives skin a porcelain-smooth, luminous finish. Locks makeup in place for hours while allowing skin to breathe.',
    description_ar: 'بودرة تثبيت ناعمة الملمس تمنح البشرة نعومة كالخزف وتثبت المكياج لساعات.',
    price: 175,
    stock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['powder', 'setting', 'luminous', 'porcelain', 'finish'],
    benefits: 'Ultra-fine milling for an imperceptible, second-skin finish. Locks foundation and concealer in place for up to 12 hours. Oil-absorbing microspheres control shine without mattifying natural radiance.',
    ingredients: 'Mica, Talc, Silica, Boron Nitride, Magnesium Myristate, Kaolin, Lauroyl Lysine, Zinc Stearate, Phenoxyethanol, Iron Oxides, Titanium Dioxide.',
    usage: 'Press a large fluffy powder brush or powder puff into the compact, tap off excess. Apply lightly over foundation in sweeping motions to set.',
    isBestseller: false,
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-008',
    name_en: 'Glow Finish Setting Powder',
    name_ar: 'بودرة تثبيت بلمسة توهج',
    slug: 'glow-finish-setting-powder',
    description_en: 'A translucent setting powder with micro-pearls of gold and rose that add a luminous, lit-from-within glow. Sets your makeup beautifully while enhancing your natural radiance.',
    description_ar: 'بودرة تثبيت شفافة بلؤلؤ الذهب والورد لتضيء بشرتك من الداخل.',
    price: 185,
    stock: 38,
    imageUrl: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['setting powder', 'glow', 'translucent', 'gold', 'luminous'],
    benefits: 'Gold micro-pearl complex reflects light for a healthy, luminous glow. Translucent formula works on all skin tones without adding colour. Extends makeup wear by up to 8 hours.',
    ingredients: 'Mica, Silica, Boron Nitride, Synthetic Fluorphlogopite, Gold (CI 77480), Titanium Dioxide (CI 77891), Phenoxyethanol, Tocopheryl Acetate.',
    usage: 'Using a large fan brush or powder brush, sweep lightly over the face in upward strokes for an all-over glow. Concentrate on the high points — cheekbones, brow bone, centre forehead — for a sculpted luminous look.',
    isBestseller: false,
    createdAt: new Date('2025-11-05'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-009',
    name_en: 'Illuminating Highlighter Palette',
    name_ar: 'باليت هايلايتر مضيء',
    slug: 'illuminating-highlighter-palette',
    description_en: 'Four shimmering highlighter shades — champagne, rose gold, pearl white, and bronze — that build from a sheer glow to a blazing strobe in one press.',
    description_ar: 'أربعة درجات من الهايلايتر المتألق — شامبانيا وذهب وردي ولؤلؤ أبيض وبرونز — لبريق مدهش.',
    price: 245,
    stock: 22,
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['highlighter', 'palette', 'glow', 'shimmer', 'champagne'],
    benefits: 'Four versatile shades buildable from natural sheen to blinding highlight. Finely milled formula blends seamlessly without harsh glitter particles. Multi-use: face, eyes, and décolletage.',
    ingredients: 'Mica, Synthetic Fluorphlogopite, Nylon-12, Dimethicone, Tocopheryl Acetate, Bismuth Oxychloride (CI 77163), Gold (CI 77480), Titanium Dioxide (CI 77891).',
    usage: "Sweep the lightest shade over the entire face as a topper. Apply champagne or rose gold to the tops of cheekbones, nose bridge, and cupid's bow for a natural glow.",
    isBestseller: true,
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2025-12-01'),
  },

  /* ─────────────── EYES ─────────────── */
  {
    id: 'demo-010',
    name_en: 'Waterproof Precision Eyeliner',
    name_ar: 'محدد عيون دقيق مقاوم للماء',
    slug: 'waterproof-precision-eyeliner',
    description_en: 'A micro-fine eyeliner that delivers razor-sharp lines with effortless control. Waterproof, smudge-proof, and sweat-resistant for all-day precision that stays exactly where you put it.',
    description_ar: 'محدد عيون بفرشاة دقيقة تمنح خطوطًا حادة مقاومة للماء والعرق طوال اليوم.',
    price: 125,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'v-010-1', productId: 'demo-010', shadeName: 'Jet Black',      hexColor: '#0A0A0A', image: null, stock: 55, sku: 'WPE-JB', sortOrder: 0 },
      { id: 'v-010-2', productId: 'demo-010', shadeName: 'Espresso Brown', hexColor: '#3D1C0E', image: null, stock: 32, sku: 'WPE-EB', sortOrder: 1 },
      { id: 'v-010-3', productId: 'demo-010', shadeName: 'Navy Midnight',  hexColor: '#0A1628', image: null, stock: 20, sku: 'WPE-NM', sortOrder: 2 },
      { id: 'v-010-4', productId: 'demo-010', shadeName: 'Forest Green',   hexColor: '#1A3A1A', image: null, stock: 14, sku: 'WPE-FG', sortOrder: 3 },
    ],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['eyeliner', 'waterproof', 'precision', 'black', 'smudge-proof'],
    benefits: 'Ultra-fine 0.01mm tip for precision lines, wings, and detailed artwork. Waterproof, sweat-proof, and humidity-resistant formula lasts 24 hours. Intense pigment delivers opacity in a single stroke.',
    ingredients: 'Aqua, Acrylates Copolymer, Carbon Black (CI 77266), Glycerin, Phenoxyethanol, Polyisobutene, Panthenol, Xanthan Gum.',
    usage: 'Shake the pen before first use. Draw a thin line as close to the lash line as possible, starting from the inner corner. For a winged look, extend from the outer corner upward at a 45-degree angle.',
    isBestseller: false,
    createdAt: new Date('2025-10-10'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-011',
    name_en: 'Volume Boost Mascara',
    name_ar: 'ماسكارا تكثيف الحجم',
    slug: 'volume-boost-mascara',
    description_en: 'Dramatic volume and intense blackness that transforms every lash from the root. A curved, XXL brush coats each lash in a single pass for lashes that look impossibly full.',
    description_ar: 'حجم درامي وسواد مكثف يحول كل رمشة من الجذر. فرشاة ضخمة منحنية تغطي كل رمشة بضربة واحدة.',
    price: 155,
    stock: 48,
    imageUrl: 'https://images.unsplash.com/photo-1527799820374-87642af6f6de?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['mascara', 'volume', 'lengthening', 'no clump', 'black'],
    benefits: 'XXL curved brush grips lashes at the root for maximum lift and volume. No-clump formula deposits even colour without weighing lashes down. Enriched with biotin and keratin to strengthen and condition lashes over time.',
    ingredients: 'Aqua, Beeswax, Carnauba Wax, Stearic Acid, Nylon-12, Carbon Black (CI 77266), Biotin, Hydrolyzed Keratin, Panthenol, Glycerin, Phenoxyethanol.',
    usage: 'Start at the base of lashes and wiggle the brush slightly to coat roots, then sweep upward in a single, fluid motion. Apply 2–3 coats for full drama, letting each coat dry slightly before the next.',
    isBestseller: true,
    createdAt: new Date('2025-09-10'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-012',
    name_en: 'Smokey Eyeshadow Palette',
    name_ar: 'باليت ظلال عيون سموكي',
    slug: 'smokey-eyeshadow-palette',
    description_en: 'Twelve ultra-blendable shades spanning neutral nudes, deep espressos, and rich bronzes. Matte, satin, and metallic finishes in one cohesive palette designed to create everything from effortless daytime to full smokey drama.',
    description_ar: '12 ظل قابل للمزج بسهولة من الدرجات المحايدة إلى البني الغامق والبرونز — ليلي ونهاري.',
    price: 320,
    stock: 18,
    imageUrl: 'https://images.unsplash.com/photo-1599733594230-6b823e54cd4a?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['eyeshadow', 'palette', 'smokey', 'bronze', 'matte', 'metallic'],
    benefits: 'Buttery, blendable formula applies like silk and blends without patchiness. 12 shades in matte, satin, and metallic finishes — endless combinations. Minimal fallout for clean, precise application.',
    ingredients: 'Mica, Talc, Boron Nitride, Nylon-12, Dimethicone, Isopropyl Myristate, Tocopherol, Phenoxyethanol, Iron Oxides (CI 77491, CI 77492, CI 77499), CI 77891.',
    usage: 'Prime lids with an eyeshadow primer for extended wear. Apply a light base shade all over the lid. Layer a mid-tone shade on the crease using a blending brush. Finish with a metallic pop on the lid centre.',
    isBestseller: false,
    createdAt: new Date('2025-10-25'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-013',
    name_en: 'Brow Definer Pencil',
    name_ar: 'قلم تحديد الحاجبين',
    slug: 'brow-definer-pencil',
    description_en: 'A micro-tip brow pencil that mimics real hair strokes with remarkable precision. Creates defined, natural-looking brows with an ultra-fine tip and features a spoolie brush for seamless blending.',
    description_ar: 'قلم حاجبين بطرف دقيق يحاكي ضربات الشعر الحقيقية لحاجبين طبيعيين ومحددين بدقة.',
    price: 115,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'v-013-1', productId: 'demo-013', shadeName: 'Blonde',       hexColor: '#C8A882', image: null, stock: 30, sku: 'BDP-BL', sortOrder: 0 },
      { id: 'v-013-2', productId: 'demo-013', shadeName: 'Taupe',        hexColor: '#8B7B6B', image: null, stock: 42, sku: 'BDP-TP', sortOrder: 1 },
      { id: 'v-013-3', productId: 'demo-013', shadeName: 'Medium Brown', hexColor: '#5C3D2A', image: null, stock: 62, sku: 'BDP-MB', sortOrder: 2 },
      { id: 'v-013-4', productId: 'demo-013', shadeName: 'Dark Brown',   hexColor: '#2E1A0F', image: null, stock: 38, sku: 'BDP-DB', sortOrder: 3 },
      { id: 'v-013-5', productId: 'demo-013', shadeName: 'Espresso',     hexColor: '#1A0A05', image: null, stock: 26, sku: 'BDP-ES', sortOrder: 4 },
    ],
    category: 'MAKEUP',
    brand: 'Besma Sevdam',
    tags: ['brow pencil', 'micro tip', 'natural', 'hair stroke', 'spoolie'],
    benefits: 'Micro-tip for hair-like strokes that look impossibly real. Waterproof and humidity-resistant formula lasts 24 hours without fading. Built-in spoolie brush to blend and tame brows naturally.',
    ingredients: 'Synthetic Wax, Isocetyl Stearoyl Stearate, Carnauba Wax, Hydrogenated Polyisobutene, Tocopherol, Iron Oxides (CI 77499, CI 77491), CI 77891.',
    usage: 'Use light, feathery strokes mimicking the direction of natural brow hairs. Start from the inner brow and work outward. Fill sparse areas last. Blend with the included spoolie brush in upward motions.',
    isBestseller: false,
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2025-12-01'),
  },

  /* ─────────────── SKINCARE ─────────────── */
  {
    id: 'demo-014',
    name_en: 'Daily Glow Hydrating Serum',
    name_ar: 'سيروم الترطيب اليومي المضيء',
    slug: 'daily-glow-hydrating-serum',
    description_en: 'A luxurious daily serum powered by three molecular weights of hyaluronic acid and a gold peptide complex that delivers deep, lasting hydration. Skin appears visibly plumper, smoother, and luminous from the first application.',
    description_ar: 'سيروم يومي فاخر بثلاثة أوزان جزيئية من الهيالورونيك أسيد ومركب ببتيدات الذهب لترطيب عميق ودائم.',
    price: 385,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'SKINCARE',
    brand: 'Besma Sevdam',
    tags: ['serum', 'hyaluronic acid', 'hydrating', 'glow', 'gold peptides', 'bestseller'],
    benefits: 'Triple-action hyaluronic acid attracts, holds, and seals moisture at every skin depth. Gold peptide complex firms and plumps skin while boosting natural radiance. Niacinamide evens skin tone and minimises the appearance of pores.',
    ingredients: 'Aqua, Glycerin, Sodium Hyaluronate (3 molecular weights), Niacinamide, Gold (CI 77480), Acetyl Hexapeptide-3, Panthenol, Allantoin, Xanthan Gum, Phenoxyethanol, Citric Acid.',
    usage: 'Apply 2–3 drops to clean, slightly damp skin morning and evening. Press gently into skin with your palms — do not rub. Follow immediately with your moisturiser to lock in the serum.',
    isBestseller: true,
    createdAt: new Date('2025-09-05'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-015',
    name_en: 'Vitamin C Brightening Cream',
    name_ar: 'كريم فيتامين سي للإشراق',
    slug: 'vitamin-c-brightening-cream',
    description_en: 'A high-performance brightening moisturiser with 15% stabilised Vitamin C that visibly fades dark spots, hyperpigmentation, and sun damage in 28 days. Reveals a radiant, even, luminous complexion.',
    description_ar: 'مرطب مُفتِّح عالي الأداء بفيتامين C مستقر بتركيز 15% يُبهت البقع الداكنة وتعرض الشمس خلال 28 يومًا.',
    price: 345,
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'SKINCARE',
    brand: 'Besma Sevdam',
    tags: ['vitamin C', 'brightening', 'dark spots', 'glow', 'moisturiser'],
    benefits: '15% stabilised Ascorbyl Glucoside penetrates deeply for maximum brightening. Visibly reduces dark spots and hyperpigmentation in as few as 28 days. Rich, non-greasy formula leaves skin soft and glowing.',
    ingredients: 'Aqua, Ascorbyl Glucoside 15%, Niacinamide, Glycerin, Squalane, Cetearyl Alcohol, Rosehip Oil, Alpha Arbutin, Ferulic Acid, Tocopherol, Hyaluronic Acid, Phenoxyethanol.',
    usage: 'Apply every morning to clean, dry skin after serum. Massage in gentle, upward circular motions until fully absorbed. Always follow with SPF 30+ during the day.',
    isBestseller: false,
    createdAt: new Date('2025-10-08'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-016',
    name_en: 'Luxury Rose Water Toner',
    name_ar: 'تونر ماء الورد الفاخر',
    slug: 'luxury-rose-water-toner',
    description_en: 'A delicate, alcohol-free toner distilled from 100% pure Bulgarian rose petals that soothes, hydrates, and prepares skin to absorb the next step of your routine. A ritual of pure luxury.',
    description_ar: 'تونر خفيف خالٍ من الكحول يُقطَّر من بتلات ورد بلغارية نقية يهدئ ويرطب البشرة.',
    price: 185,
    stock: 70,
    imageUrl: 'https://images.unsplash.com/photo-1557804483-ef3e8c6b5e25?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'SKINCARE',
    brand: 'Besma Sevdam',
    tags: ['toner', 'rose water', 'soothing', 'Bulgarian rose', 'alcohol-free'],
    benefits: 'Pure Bulgarian rose distillate soothes redness and calms sensitive skin. Balances pH for optimal absorption of subsequent skincare steps. Alcohol-free formula safe for daily use on all skin types including sensitive.',
    ingredients: 'Rosa Damascena (Bulgarian Rose) Flower Water 95%, Sodium Hyaluronate, Glycerin, Allantoin, Panthenol, Rosa Canina (Rosehip) Extract, Phenoxyethanol, Citric Acid.',
    usage: 'After cleansing, saturate a cotton pad and gently sweep upward across the face and neck. Alternatively, mist directly onto skin for an instant refresh. Follow with serum and moisturiser.',
    isBestseller: false,
    createdAt: new Date('2025-10-30'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-017',
    name_en: 'Overnight Repair Cream',
    name_ar: 'كريم الإصلاح الليلي',
    slug: 'overnight-repair-cream',
    description_en: 'A rich, restorative night cream that works while you sleep to rebuild the skin barrier, erase signs of fatigue, and replenish deep hydration. Wake up to visibly firmer, softer, and more radiant skin every morning.',
    description_ar: 'كريم ليلي مُجدِّد غني يعمل أثناء النوم لإصلاح حاجز البشرة ومحو علامات الإرهاق وإعادة الترطيب.',
    price: 310,
    stock: 28,
    imageUrl: 'https://images.unsplash.com/photo-1583241800698-e8ab01830a25?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'SKINCARE',
    brand: 'Besma Sevdam',
    tags: ['night cream', 'repair', 'overnight', 'firming', 'hydrating'],
    benefits: 'Retinol-alternative complex stimulates natural cell renewal without irritation. Shea butter and ceramides rebuild and strengthen the protective skin barrier overnight. Peptide complex firms and plumps skin for a visibly lifted appearance by morning.',
    ingredients: 'Aqua, Shea Butter, Ceramide NP, Bakuchiol (Retinol alternative), Niacinamide, Matrixyl 3000 Peptide, Squalane, Glycerin, Allantoin, Hyaluronic Acid, Phenoxyethanol.',
    usage: 'As the final step of your evening routine, apply a generous amount to face and neck after your serum. Warm between your palms first for better absorption. Press gently into skin — do not rub. Leave overnight.',
    isBestseller: true,
    createdAt: new Date('2025-09-25'),
    updatedAt: new Date('2025-12-01'),
  },

  /* ─────────────── TOOLS & ACCESSORIES ─────────────── */
  {
    id: 'demo-018',
    name_en: 'Premium Beauty Blender',
    name_ar: 'إسفنجة المكياج الفاخرة',
    slug: 'premium-beauty-blender',
    description_en: 'A silky-smooth, ultra-bouncy applicator that melts liquid and cream foundation seamlessly into skin. Patented micro-foam technology holds less product and deposits more — zero waste, perfect finish every time.',
    description_ar: 'إسفنجة تطبيق ناعمة فائقة المرونة تمزج كريم الأساس السائل والكريمي بسلاسة مع البشرة.',
    price: 95,
    stock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1567721913486-6585f069b3e7?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'TOOLS',
    brand: 'Besma Sevdam',
    tags: ['beauty blender', 'sponge', 'applicator', 'flawless', 'foundation'],
    benefits: 'Micro-foam technology deposits maximum product for less waste. Works wet or dry — dampen for a dewy finish, use dry for full coverage. Ergonomic teardrop shape reaches all facial contours.',
    ingredients: 'Hydrophilic Polyurethane Foam, Proprietary Micro-Pore Technology. Latex-free, vegan, cruelty-free.',
    usage: 'For best results, dampen with water and squeeze out all excess. Bounce (do not drag) onto skin in rapid dabbing motions. Start at the centre and work outward. Clean after each use with a gentle cleanser.',
    isBestseller: false,
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-019',
    name_en: 'Gold Makeup Brush Set – 12 Pieces',
    name_ar: 'طقم فرش المكياج الذهبي – 12 قطعة',
    slug: 'gold-makeup-brush-set-12pc',
    description_en: 'A complete professional brush collection with gold-lacquered handles and densely packed, ultra-soft synthetic bristles. Twelve brushes for face, eye, and lip application — everything you need for a flawless, professional finish.',
    description_ar: 'مجموعة فرش احترافية كاملة بمقابض مطلية بالذهب وشعيرات صناعية فائقة النعومة — 12 فرشاة للوجه والعيون والشفتين.',
    price: 495,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'TOOLS',
    brand: 'Besma Sevdam',
    tags: ['brush set', 'professional', 'gold', '12 piece', 'synthetic', 'makeup brushes'],
    benefits: 'Dense, synthetic bristles hold and deposit product evenly for a professional, streak-free finish. Cruelty-free synthetic fibres suitable for both powder and liquid formulas. Gold-lacquered handles provide luxurious weight and balance for precise control.',
    ingredients: 'Handle: Sustainable Beechwood with 24K Gold Lacquer Coating. Bristles: Cruelty-free Synthetic Taklon Fibres. Ferrule: Polished Brass with Gold Plating.',
    usage: 'Use each brush for its designated purpose for best results. Tap off excess product before applying to face. Clean synthetic brushes weekly with a gentle soap or brush cleanser. Rinse with lukewarm water, reshape bristles, and lay flat to dry.',
    isBestseller: true,
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2025-12-01'),
  },

  {
    id: 'demo-020',
    name_en: 'Luxury Compact Mirror',
    name_ar: 'مرآة مدمجة فاخرة',
    slug: 'luxury-compact-mirror',
    description_en: 'A gold-plated, double-sided compact mirror with 1× and 5× magnification. An heirloom-quality accessory encased in soft-touch rose gold metal with an engraved floral motif on the lid.',
    description_ar: 'مرآة مدمجة ذهبية مزدوجة الجانب بتكبير 1× و5× — ملحقة بجودة الإرث في غلاف معدني ذهبي وردي.',
    price: 195,
    stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'TOOLS',
    brand: 'Besma Sevdam',
    tags: ['mirror', 'compact', 'gold', 'magnifying', '5x', 'luxury accessory'],
    benefits: 'Dual-sided design: 1× for overall makeup, 5× for precision detail work. Premium glass for crystal-clear, distortion-free reflection. Soft-hinge mechanism opens and closes with a satisfying, luxury click.',
    ingredients: 'Zinc Alloy Casing with 24K Gold Plating, Premium Optical Glass Mirror, Soft-Touch Velvet Interior Lining.',
    usage: 'Use the regular 1× mirror for overall foundation, contouring, and blush application. Switch to the 5× magnifying side for precise eyeliner, mascara, and detailed lip work.',
    isBestseller: false,
    createdAt: new Date('2025-11-12'),
    updatedAt: new Date('2025-12-01'),
  },
]

/* Featured (first 4 bestsellers) for homepage Best Sellers */
export const DEMO_FEATURED = DEMO_PRODUCTS.filter((p) => p.isBestseller).slice(0, 4)

/* New Arrivals — most recently added */
export const DEMO_NEW_ARRIVALS = [...DEMO_PRODUCTS]
  .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
  .slice(0, 4)
