import type { Product } from '@/types'

/*
  BESMA SEVDAM — Demo product catalog.
  Real products first (confirmed from brand catalog), followed by supplementary items.
  Images: Unsplash beauty photography as placeholders — replace via admin panel with real Cloudinary URLs.
  Variant products use stock:0 — individual stock lives on each variant.
*/

export const DEMO_PRODUCTS: Product[] = [

  /* ─────────────────── REAL BESMA SEVDAM PRODUCTS ─────────────────── */

  {
    id: 'bs-001',
    name_en: 'DualGlow Complexion Duo',
    name_ar: 'ديوال غلو كومبليكسيون دو',
    slug: 'dualglow-complexion-duo',
    description_en: 'The hero foundation of Besma Sevdam. DualGlow delivers a luminous, skin-like finish that photographs beautifully and wears all day. Buildable from medium to full coverage — your skin, perfected.',
    description_ar: 'أساس Besma Sevdam الأيقوني. يمنح DualGlow لمسة نهائية مضيئة تشبه البشرة الطبيعية وتدوم طوال اليوم. تغطية قابلة للبناء من المتوسطة إلى الكاملة.',
    price: 800,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1587052755018-c75ca8f28b16?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'bsv-001-1', productId: 'bs-001', shadeName: 'V40',  hexColor: '#D4956A', image: null, stock: 35, sku: 'DGC-V40',  sortOrder: 0 },
      { id: 'bsv-001-2', productId: 'bs-001', shadeName: 'V80',  hexColor: '#A86845', image: null, stock: 28, sku: 'DGC-V80',  sortOrder: 1 },
      { id: 'bsv-001-3', productId: 'bs-001', shadeName: 'V120', hexColor: '#7A4830', image: null, stock: 22, sku: 'DGC-V120', sortOrder: 2 },
    ],
    category: 'FOUNDATION',
    brand: 'Besma Sevdam',
    tags: ['foundation', 'dualglow', 'complexion', 'coverage', 'bestseller', 'hero'],
    benefits: 'Buildable coverage — medium to full in just two layers. Luminous finish that photographs beautifully in all lighting. Long-wearing formula that stays flawless for 14+ hours. Suitable for medium to deep skin tones.',
    ingredients: 'Aqua, Cyclopentasiloxane, Dimethicone, Glycerin, Titanium Dioxide (CI 77891), Niacinamide, Squalane, Phenoxyethanol, Iron Oxides (CI 77491, CI 77492, CI 77499).',
    usage: 'Apply to clean, moisturised skin with a foundation brush or damp beauty blender. Start at the centre of the face and blend outward. Build where needed. Set with Besma Sevdam Loose Powder for extended wear.',
    isBestseller: true, isOffer: false, salePrice: null,
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2026-01-01'),
  },

  {
    id: 'bs-002',
    name_en: 'Mate Liquid Lipstick',
    name_ar: 'ميت — أحمر شفاه سائل مطفأ',
    slug: 'mate-liquid-lipstick',
    description_en: 'The original. Besma Sevdam Mate is a transfer-proof matte liquid lipstick that commands the room. Rich, high-impact pigment sets in 60 seconds to a bold finish that stays put from morning to night.',
    description_ar: 'الأصيل. Mate من Besma Sevdam أحمر شفاه سائل مطفأ مقاوم للانتقال. تصبغ عالي التأثير يثبت في 60 ثانية.',
    price: 500,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1631214524020-3c69888e0a66?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'bsv-002-1', productId: 'bs-002', shadeName: 'Wine',     hexColor: '#6B1A2A', image: null, stock: 45, sku: 'MLL-WINE', sortOrder: 0 },
      { id: 'bsv-002-2', productId: 'bs-002', shadeName: 'Bordeaux', hexColor: '#5C1C3A', image: null, stock: 30, sku: 'MLL-BORD', sortOrder: 1 },
      { id: 'bsv-002-3', productId: 'bs-002', shadeName: 'Rose Nude', hexColor: '#C4927A', image: null, stock: 38, sku: 'MLL-ROSE', sortOrder: 2 },
      { id: 'bsv-002-4', productId: 'bs-002', shadeName: 'Mauve',    hexColor: '#8B5E72', image: null, stock: 22, sku: 'MLL-MAUV', sortOrder: 3 },
    ],
    category: 'LIPSTICK',
    brand: 'Besma Sevdam',
    tags: ['lipstick', 'matte', 'liquid', 'transfer-proof', 'bestseller', 'bold'],
    benefits: 'Transfer-proof and kiss-proof from the first hour. Ultra-rich pigment — full opacity in a single swipe. Comfortable matte finish that does not dry out lips. Lasts 12+ hours without touch-ups.',
    ingredients: 'Isododecane, Dimethicone, Trimethylsiloxysilicate, Tocopherol (Vitamin E), Candelilla Wax, Castor Oil, Mica, CI 15850, CI 77891.',
    usage: 'Apply directly from the applicator wand, starting from the centre of the upper lip. Follow the natural lip line. Allow 60 seconds to set completely before pressing lips together.',
    isBestseller: true, isOffer: false, salePrice: null,
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2026-01-01'),
  },

  {
    id: 'bs-003',
    name_en: 'Loose Powder',
    name_ar: 'بودرة فضفاضة',
    slug: 'loose-powder',
    description_en: 'Besma Sevdam Loose Powder. Ultra-fine setting powder that blurs every imperfection and locks your makeup in place for hours. Available in three translucent shades that work beautifully on every skin tone.',
    description_ar: 'بودرة Besma Sevdam الفضفاضة. بودرة تثبيت فائقة النعومة تطمس الشوائب وتثبت مكياجك لساعات. متوفرة بثلاث درجات شفافة.',
    price: 750,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'bsv-003-1', productId: 'bs-003', shadeName: 'Pink',   hexColor: '#E8C4C4', image: null, stock: 40, sku: 'LPW-PINK',  sortOrder: 0 },
      { id: 'bsv-003-2', productId: 'bs-003', shadeName: 'Ivory',  hexColor: '#F5EDD4', image: null, stock: 55, sku: 'LPW-IVOR',  sortOrder: 1 },
      { id: 'bsv-003-3', productId: 'bs-003', shadeName: 'Butter', hexColor: '#E8CFA0', image: null, stock: 48, sku: 'LPW-BUTT',  sortOrder: 2 },
    ],
    category: 'POWDER',
    brand: 'Besma Sevdam',
    tags: ['powder', 'setting', 'loose powder', 'matte', 'blurring', 'bestseller'],
    benefits: 'Ultra-fine milling for an imperceptible, second-skin finish. Blurs pores and fine lines for a porcelain-smooth look. Sets foundation and concealer for 12+ hour wear. Available in Pink (brightening), Ivory (neutral), and Butter (warm).',
    ingredients: 'Talc, Mica, Silica, Boron Nitride, Magnesium Myristate, Zinc Stearate, Kaolin, Tocopheryl Acetate, Phenoxyethanol, Iron Oxides, Titanium Dioxide.',
    usage: 'After foundation and concealer, press a powder brush or puff into the powder and tap off excess. Apply in light, sweeping motions across the face. Focus under the eyes, on the T-zone, and anywhere you need extra staying power.',
    isBestseller: true, isOffer: false, salePrice: null,
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2026-01-01'),
  },

  {
    id: 'bs-004',
    name_en: 'Eyeliner',
    name_ar: 'محدد العيون',
    slug: 'eyeliner-besma-sevdam',
    description_en: 'The Besma Sevdam Eyeliner. A precision felt-tip pen that delivers razor-sharp lines in a single stroke. Intensely black. Waterproof. Smudge-proof. The only eyeliner you will ever need.',
    description_ar: 'محدد عيون Besma Sevdam. قلم فيلت دقيق يرسم خطوطًا حادة بضربة واحدة. أسود مكثف. مقاوم للماء والمسح.',
    price: 500,
    stock: 75,
    imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'EYELINER',
    brand: 'Besma Sevdam',
    tags: ['eyeliner', 'waterproof', 'felt tip', 'precision', 'black', 'new'],
    benefits: 'Ultra-fine felt tip for lines of any thickness — from hairline to bold. Intense jet-black pigment, fully opaque in one pass. Waterproof and smudge-proof formula lasts 24 hours. Dries in seconds — no waiting.',
    ingredients: 'Aqua, Acrylates Copolymer, Carbon Black (CI 77266), Glycerin, Phenoxyethanol, Polyisobutene, Panthenol, Xanthan Gum.',
    usage: 'Hold close to the lash line and draw from the inner corner outward. For a wing, extend past the outer corner and flick upward. Layer for deeper intensity. Remove with an oil-based remover.',
    isBestseller: false, isOffer: false, salePrice: null,
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2026-01-01'),
  },

  {
    id: 'bs-005',
    name_en: 'Gloss Blowzy',
    name_ar: 'غلوس بلوزي — جلوس الشفاه المرطب',
    slug: 'gloss-blowzy',
    description_en: 'Gloss Blowzy by Besma Sevdam. A luxuriously moisturising lip gloss that gives lips a full, glass-like shine. Non-sticky. Deeply hydrating. Wearable alone or layered over lipstick for irresistible dimension.',
    description_ar: 'غلوس Blowzy من Besma Sevdam. جلوس شفاه مرطب يمنح الشفتين لمعانًا زجاجيًا كاملاً. غير لزج. مرطب بعمق.',
    price: 499,
    stock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1620803366004-119b57f54cd6?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'bsv-005-1', productId: 'bs-005', shadeName: 'Coral',    hexColor: '#E8735A', image: null, stock: 30, sku: 'GBL-CORAL', sortOrder: 0 },
      { id: 'bsv-005-2', productId: 'bs-005', shadeName: 'Champagne', hexColor: '#D4B88A', image: null, stock: 25, sku: 'GBL-CHMP',  sortOrder: 1 },
      { id: 'bsv-005-3', productId: 'bs-005', shadeName: 'Rosé',      hexColor: '#D4929A', image: null, stock: 20, sku: 'GBL-ROSE',  sortOrder: 2 },
    ],
    category: 'LIP_GLOSS',
    brand: 'Besma Sevdam',
    tags: ['lip gloss', 'moisturizing', 'glossy', 'hydrating', 'new'],
    benefits: 'Glass-shine finish that makes lips look fuller and more defined. Non-sticky formula stays comfortable for hours. Hyaluronic acid complex deeply hydrates and plumps lip texture over time. Vitamin E conditions and protects.',
    ingredients: 'Polybutene, Hydrogenated Polyisobutene, Dipentaerythrityl Hexacaprylate, Hyaluronic Acid, Tocopherol, Mica, CI 15850, CI 77000.',
    usage: 'Apply directly from the doe-foot applicator starting at the centre and sweeping outward. Wear alone for a fresh, glossy look or layer over Mate Lipstick for extra dimension and shine.',
    isBestseller: false, isOffer: false, salePrice: null,
    createdAt: new Date('2025-12-15'),
    updatedAt: new Date('2026-01-01'),
  },

  {
    id: 'bs-006',
    name_en: 'Mascara Waterproof Double Volume',
    name_ar: 'ماسكارا مضاعفة الحجم مقاومة للماء',
    slug: 'mascara-waterproof-double-volume',
    description_en: 'Double the volume. Zero clumps. The Besma Sevdam Mascara is a waterproof volumising formula that builds dramatically full lashes with a professional curved brush. Smudge-proof and humidity-resistant all day.',
    description_ar: 'حجم مضاعف. بدون تكتلات. ماسكارا Besma Sevdam المقاومة للماء تُضاعف كثافة الرموش بدقة احترافية.',
    price: 500,
    stock: 55,
    imageUrl: 'https://images.unsplash.com/photo-1527799820374-87642af6f6de?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'MASCARA',
    brand: 'Besma Sevdam',
    tags: ['mascara', 'waterproof', 'volume', 'double volume', 'bestseller'],
    benefits: 'Double-volume curved brush coats every lash from root to tip in one swipe. Waterproof and humidity-resistant for all-day drama. No-clump formula separates and lengthens without heaviness. Enriched with keratin to strengthen lashes over time.',
    ingredients: 'Aqua, Beeswax, Carnauba Wax, Stearic Acid, Nylon-12, Carbon Black (CI 77266), Hydrolyzed Keratin, Panthenol, Glycerin, Phenoxyethanol.',
    usage: 'Wiggle the brush at the base of lashes, then sweep upward in a single fluid motion. Apply 2–3 coats for maximum volume. Let each coat dry 30 seconds before applying the next.',
    isBestseller: true, isOffer: false, salePrice: null,
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2026-01-01'),
  },

  /* ─────────────── SUPPLEMENTARY MAKEUP ─────────────── */

  {
    id: 'demo-007',
    name_en: 'Full Coverage Concealer',
    name_ar: 'كونسيلر تغطية كاملة',
    slug: 'full-coverage-concealer',
    description_en: 'A creamy, full-coverage concealer that erases dark circles, blemishes, and redness instantly. Flexible formula that moves with your skin — no creasing, no settling into fine lines.',
    description_ar: 'كونسيلر كريمي بتغطية كاملة يمحو الهالات السوداء والبثور والاحمرار على الفور.',
    price: 450,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'v-007-1', productId: 'demo-007', shadeName: 'Ivory',    hexColor: '#F5EBD8', image: null, stock: 45, sku: 'FCC-IV', sortOrder: 0 },
      { id: 'v-007-2', productId: 'demo-007', shadeName: 'Beige',    hexColor: '#EDD4AA', image: null, stock: 50, sku: 'FCC-BG', sortOrder: 1 },
      { id: 'v-007-3', productId: 'demo-007', shadeName: 'Sand',     hexColor: '#D4B887', image: null, stock: 38, sku: 'FCC-SA', sortOrder: 2 },
      { id: 'v-007-4', productId: 'demo-007', shadeName: 'Honey',    hexColor: '#C49A60', image: null, stock: 30, sku: 'FCC-HN', sortOrder: 3 },
      { id: 'v-007-5', productId: 'demo-007', shadeName: 'Chestnut', hexColor: '#A67848', image: null, stock: 20, sku: 'FCC-CH', sortOrder: 4 },
    ],
    category: 'CONCEALER',
    brand: 'Besma Sevdam',
    tags: ['concealer', 'full coverage', 'dark circles', 'no crease'],
    benefits: 'Full coverage in a single layer — conceals dark circles, hyperpigmentation, and blemishes. Caffeine-infused to de-puff and brighten the under-eye area. Flexible formula moves with skin without creasing.',
    ingredients: 'Cyclopentasiloxane, Dimethicone, Isododecane, Trimethylsiloxysilicate, Caffeine, Niacinamide, Peptides Complex, Iron Oxides, Titanium Dioxide (CI 77891).',
    usage: 'Tap under eyes or on blemishes using your ring finger. Blend gently by tapping. Set with Loose Powder for extended wear.',
    isBestseller: false, isOffer: false, salePrice: null,
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2026-01-01'),
  },

  {
    id: 'demo-008',
    name_en: 'Illuminating Highlighter',
    name_ar: 'هايلايتر مضيء',
    slug: 'illuminating-highlighter',
    description_en: 'A finely milled highlighter powder that adds a breathtaking lit-from-within glow. Champagne and gold micro-pearls catch light at every angle for a luminous, sculpted finish.',
    description_ar: 'هايلايتر ناعم الطحن يضيف توهجًا مذهلاً من الداخل. لآلئ ذهبية وشامبانيا تعكس الضوء من كل زاوية.',
    price: 600,
    stock: 22,
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'HIGHLIGHTER',
    brand: 'Besma Sevdam',
    tags: ['highlighter', 'glow', 'shimmer', 'champagne', 'sculpting'],
    benefits: 'Micro-pearl complex delivers a luminous glow that is never glittery or harsh. Buildable from a subtle daytime sheen to a blazing evening highlight. Multi-use: cheekbones, eyes, décolletage.',
    ingredients: 'Mica, Synthetic Fluorphlogopite, Nylon-12, Dimethicone, Tocopheryl Acetate, Gold (CI 77480), Titanium Dioxide (CI 77891).',
    usage: 'Apply with a fan brush or highlighting brush to the tops of cheekbones, brow bone, inner corner of eyes, and nose bridge. Build gradually for more intensity.',
    isBestseller: false, isOffer: false, salePrice: null,
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2026-01-01'),
  },

  {
    id: 'demo-009',
    name_en: 'Brow Definer Pencil',
    name_ar: 'قلم تحديد الحاجبين',
    slug: 'brow-definer-pencil',
    description_en: 'A micro-tip brow pencil that mimics real hair strokes with remarkable precision. Creates defined, natural-looking brows with an ultra-fine tip and built-in spoolie for seamless blending.',
    description_ar: 'قلم حاجبين بطرف دقيق يحاكي ضربات الشعر الحقيقية لحاجبين طبيعيين محددين بدقة.',
    price: 400,
    stock: 0,
    imageUrl: 'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: true,
    variants: [
      { id: 'v-009-1', productId: 'demo-009', shadeName: 'Taupe',        hexColor: '#8B7B6B', image: null, stock: 42, sku: 'BDP-TP', sortOrder: 0 },
      { id: 'v-009-2', productId: 'demo-009', shadeName: 'Medium Brown', hexColor: '#5C3D2A', image: null, stock: 62, sku: 'BDP-MB', sortOrder: 1 },
      { id: 'v-009-3', productId: 'demo-009', shadeName: 'Dark Brown',   hexColor: '#2E1A0F', image: null, stock: 38, sku: 'BDP-DB', sortOrder: 2 },
      { id: 'v-009-4', productId: 'demo-009', shadeName: 'Espresso',     hexColor: '#1A0A05', image: null, stock: 26, sku: 'BDP-ES', sortOrder: 3 },
    ],
    category: 'EYELINER',
    brand: 'Besma Sevdam',
    tags: ['brow pencil', 'micro tip', 'natural', 'hair stroke', 'spoolie'],
    benefits: 'Micro-tip for hair-like strokes that look impossibly real. Waterproof formula lasts 24 hours without fading. Built-in spoolie brush blends and tames brows naturally.',
    ingredients: 'Synthetic Wax, Isocetyl Stearoyl Stearate, Carnauba Wax, Hydrogenated Polyisobutene, Tocopherol, Iron Oxides (CI 77499, CI 77491), CI 77891.',
    usage: 'Use light, feathery strokes in the direction of natural brow hairs. Start from the inner brow and work outward. Blend with the included spoolie brush.',
    isBestseller: false, isOffer: false, salePrice: null,
    createdAt: new Date('2025-11-25'),
    updatedAt: new Date('2026-01-01'),
  },

  /* ─────────────── SKINCARE ─────────────── */

  {
    id: 'demo-010',
    name_en: 'Daily Glow Hydrating Serum',
    name_ar: 'سيروم الترطيب اليومي المضيء',
    slug: 'daily-glow-hydrating-serum',
    description_en: 'A luxurious daily serum powered by three molecular weights of hyaluronic acid and a gold peptide complex. Skin appears visibly plumper, smoother, and luminous from the first application.',
    description_ar: 'سيروم يومي فاخر بثلاثة أوزان جزيئية من الهيالورونيك أسيد ومركب ببتيدات الذهب لترطيب عميق.',
    price: 850,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'PRIMER',
    brand: 'Besma Sevdam',
    tags: ['serum', 'hyaluronic acid', 'hydrating', 'glow', 'gold peptides'],
    benefits: 'Triple hyaluronic acid attracts, holds, and seals moisture at every skin depth. Gold peptide complex firms and boosts radiance. Niacinamide evens skin tone and minimises pores.',
    ingredients: 'Aqua, Glycerin, Sodium Hyaluronate (3 molecular weights), Niacinamide, Gold (CI 77480), Acetyl Hexapeptide-3, Panthenol, Allantoin, Xanthan Gum, Phenoxyethanol, Citric Acid.',
    usage: 'Apply 2–3 drops to clean, slightly damp skin morning and evening. Press gently into skin with your palms. Follow with moisturiser.',
    isBestseller: true, isOffer: false, salePrice: null,
    createdAt: new Date('2025-09-10'),
    updatedAt: new Date('2026-01-01'),
  },

  {
    id: 'demo-011',
    name_en: 'Vitamin C Brightening Cream',
    name_ar: 'كريم فيتامين سي للإشراق',
    slug: 'vitamin-c-brightening-cream',
    description_en: 'A high-performance brightening moisturiser with 15% stabilised Vitamin C. Visibly fades dark spots and hyperpigmentation in 28 days. Reveals a radiant, even, luminous complexion.',
    description_ar: 'مرطب مُفتِّح بفيتامين C بتركيز 15% يُبهت البقع الداكنة في 28 يومًا ويكشف عن بشرة مضيئة متجانسة.',
    price: 900,
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'PRIMER',
    brand: 'Besma Sevdam',
    tags: ['vitamin C', 'brightening', 'dark spots', 'glow', 'moisturiser'],
    benefits: '15% stabilised Ascorbyl Glucoside brightens and reduces dark spots in 28 days. Ferulic acid and Vitamin E protect against oxidative stress. Rich formula nourishes skin while it works.',
    ingredients: 'Aqua, Ascorbyl Glucoside 15%, Niacinamide, Glycerin, Squalane, Cetearyl Alcohol, Rosehip Oil, Alpha Arbutin, Ferulic Acid, Tocopherol, Hyaluronic Acid, Phenoxyethanol.',
    usage: 'Apply every morning to clean, dry skin after serum. Massage in upward circular motions. Always follow with SPF 30+ during the day.',
    isBestseller: false, isOffer: false, salePrice: null,
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2026-01-01'),
  },

  {
    id: 'demo-012',
    name_en: 'Overnight Repair Cream',
    name_ar: 'كريم الإصلاح الليلي',
    slug: 'overnight-repair-cream',
    description_en: 'A rich, restorative night cream that works while you sleep to rebuild the skin barrier and replenish deep hydration. Wake up to visibly firmer, softer, and more radiant skin every morning.',
    description_ar: 'كريم ليلي مُجدِّد غني يعمل أثناء النوم لإصلاح حاجز البشرة وإعادة الترطيب العميق.',
    price: 950,
    stock: 28,
    imageUrl: 'https://images.unsplash.com/photo-1583241800698-e8ab01830a25?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'PRIMER',
    brand: 'Besma Sevdam',
    tags: ['night cream', 'repair', 'overnight', 'firming', 'hydrating'],
    benefits: 'Bakuchiol (retinol alternative) stimulates cell renewal without irritation. Ceramides and shea butter rebuild the skin barrier overnight. Peptide complex firms and plumps for a visibly lifted appearance by morning.',
    ingredients: 'Aqua, Shea Butter, Ceramide NP, Bakuchiol, Niacinamide, Matrixyl 3000, Squalane, Glycerin, Allantoin, Hyaluronic Acid, Phenoxyethanol.',
    usage: 'As the final step of your evening routine, apply generously to face and neck. Warm between your palms first. Press gently into skin and leave overnight.',
    isBestseller: true, isOffer: false, salePrice: null,
    createdAt: new Date('2025-09-25'),
    updatedAt: new Date('2026-01-01'),
  },

  /* ─────────────── TOOLS ─────────────── */

  {
    id: 'demo-013',
    name_en: 'Premium Beauty Blender',
    name_ar: 'إسفنجة المكياج الفاخرة',
    slug: 'premium-beauty-blender',
    description_en: 'A silky-smooth, ultra-bouncy applicator that melts liquid and cream foundation seamlessly into skin. Micro-foam technology holds less product and deposits more — zero waste, perfect finish.',
    description_ar: 'إسفنجة ناعمة فائقة المرونة تمزج كريم الأساس بسلاسة مع البشرة. تقنية مسامية دقيقة لتطبيق مثالي.',
    price: 350,
    stock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1567721913486-6585f069b3e7?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'POWDER',
    brand: 'Besma Sevdam',
    tags: ['beauty blender', 'sponge', 'applicator', 'flawless', 'foundation'],
    benefits: 'Micro-foam deposits maximum product for less waste. Works wet (dewy finish) or dry (full coverage). Ergonomic teardrop shape reaches all facial contours.',
    ingredients: 'Hydrophilic Polyurethane Foam. Latex-free, vegan, cruelty-free.',
    usage: 'Dampen with water and squeeze out all excess. Bounce (do not drag) onto skin in rapid dabbing motions from the centre outward. Clean after each use with a gentle soap.',
    isBestseller: false, isOffer: false, salePrice: null,
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2026-01-01'),
  },

  {
    id: 'demo-014',
    name_en: 'Gold Makeup Brush Set — 12 Pieces',
    name_ar: 'طقم فرش المكياج الذهبي — 12 قطعة',
    slug: 'gold-makeup-brush-set-12pc',
    description_en: 'A complete professional brush collection with gold-lacquered handles and densely packed, ultra-soft synthetic bristles. Twelve brushes for face, eye, and lip — everything for a flawless professional finish.',
    description_ar: 'مجموعة فرش احترافية بمقابض ذهبية وشعيرات صناعية فائقة النعومة — 12 فرشاة للوجه والعيون والشفتين.',
    price: 1200,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'POWDER',
    brand: 'Besma Sevdam',
    tags: ['brush set', 'professional', 'gold', '12 piece', 'synthetic'],
    benefits: 'Dense synthetic bristles apply product evenly for a professional finish. Cruelty-free fibres work with both powder and liquid formulas. Gold handles provide luxurious weight and control.',
    ingredients: 'Handle: Sustainable Beechwood with Gold Lacquer. Bristles: Cruelty-free Synthetic Taklon. Ferrule: Polished Brass with Gold Plating.',
    usage: 'Use each brush for its designated purpose. Tap off excess product before applying to face. Clean weekly with gentle brush cleanser. Rinse, reshape, and lay flat to dry.',
    isBestseller: true, isOffer: false, salePrice: null,
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2026-01-01'),
  },

  /* ─────────────── ADDITIONAL SKINCARE ─────────────── */

  {
    id: 'demo-015',
    name_en: 'Luxury Rose Water Toner',
    name_ar: 'تونر ماء الورد الفاخر',
    slug: 'luxury-rose-water-toner',
    description_en: 'An alcohol-free toner distilled from 100% pure Bulgarian rose petals. Soothes, hydrates, and prepares skin to absorb the next step of your routine. A ritual of pure luxury.',
    description_ar: 'تونر خالٍ من الكحول يُقطَّر من بتلات ورد بلغارية نقية يهدئ ويرطب البشرة.',
    price: 600,
    stock: 70,
    imageUrl: 'https://images.unsplash.com/photo-1557804483-ef3e8c6b5e25?w=800&q=80&auto=format&fit=crop',
    gallery: [],
    hasVariants: false,
    variants: [],
    category: 'PRIMER',
    brand: 'Besma Sevdam',
    tags: ['toner', 'rose water', 'soothing', 'Bulgarian rose', 'alcohol-free'],
    benefits: 'Pure Bulgarian rose distillate soothes redness and calms sensitive skin. Balances pH for optimal absorption of next steps. Alcohol-free — safe for daily use on all skin types.',
    ingredients: 'Rosa Damascena Flower Water 95%, Sodium Hyaluronate, Glycerin, Allantoin, Panthenol, Rosa Canina Extract, Phenoxyethanol, Citric Acid.',
    usage: 'After cleansing, saturate a cotton pad and sweep upward across the face and neck. Or mist directly onto skin for an instant refresh. Follow with serum and moisturiser.',
    isBestseller: false, isOffer: false, salePrice: null,
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2026-01-01'),
  },
]

/* Featured (first 4 bestsellers) for homepage Best Sellers */
export const DEMO_FEATURED = DEMO_PRODUCTS.filter((p) => p.isBestseller).slice(0, 4)

/* New Arrivals — most recently created */
export const DEMO_NEW_ARRIVALS = [...DEMO_PRODUCTS]
  .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
  .slice(0, 4)
